name: app_logger
description: A reusable logging package for Flutter applications using Talker
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.5.3
  flutter: ^3.32.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  talker_flutter: ^4.8.4
  riverpod: ^2.6.1
  firebase_crashlytics: ^4.3.9
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.5.3
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  flutter_lints: ^6.0.0
  yumemi_lints: ^4.1.1

flutter:
