[tools]
flutter = "3.32.8"
node = "22.18.0"
bun = "1.2.17"

# Main workflow tasks
[tasks.dev]
description = "Complete development workflow"
run = """
melos run get
melos run gen
melos run analyze
melos run test
"""

[tasks.setup]
description = "Initial project setup"
run = """
melos bootstrap
bun install
"""

[tasks.quality]
description = "Code quality workflow"
run = """
melos run ci:format
melos run analyze
melos run analyze:slang
melos run test
"""

[tasks.ci-check]
description = "Complete CI workflow"
run = """
set -e
melos run format
if [ $? -ne 0 ]; then
    echo "Formatting changes detected. Please commit the changes and run again."
    exit 1
fi
melos run analyze
melos run test
bun run ci:check
"""

[tasks.analyze]
description = "Static analysis"
run = "melos run analyze"

[tasks.analyze-slang]
description = "Translation validation"
run = "melos run analyze:slang"

[tasks.test]
description = "Run tests"
run = "melos run test"

# Formatting tasks
[tasks.format]
description = "Format all files"
run = """
melos run format
bun run format
"""

[tasks.clean-branch]
description = "Clean git branches/worktrees"
run = "./scripts/clean-branch.sh"