name: app_preferences
description: Application preferences management package for locale and theme settings.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.8.1
  flutter: 3.32.8

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  slang: ^4.7.2
  slang_flutter: ^4.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  slang_build_runner: ^4.7.0
  yumemi_lints: ^4.1.1
