name: setlist_parser
description: A setlist parser command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  args: ^2.7.0
  cores:
    path: ../../packages/cores

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  yumemi_lints: ^4.1.1
