include: package:yumemi_lints/flutter/3.32/recommended.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  # NOTE:
  # custom_lint is disabled due to error "pub is not an AOT snapshot, it cannot be run with 'dartaotruntime'"
  # This error occurs when custom_lint tries to run "pub get" in the client project
  # TODO: Re-enable custom_lint when the underlying issue is resolved
  # plugins:
  #   - custom_lint

formatter:
  trailing_commas: preserve
