name: cores
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  lints: ^6.0.0
  test: ^1.24.0
  yumemi_lints: ^4.1.1
